name: build kernel on GitHub workflows

on:

 workflow_dispatch

    

  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Checkout source

      with:

        submodules: recursive

      run: sudo apt update -y && sudo apt upgrade -y

    - name: Update Environment 

      run: |

      

sudo apt install -y git-core gnupg flex be bison build-essential zip \ curl 211big-dev gcc-multilib gt-multilib libc6-dev-1386 11b32ncurses5-dev. V

x11proto-core-dev libx11-dev jq 11b3221-dev libxml2-utils V xsitproc unzip fontconfig imagemagick python2 python3 python3-pip python3-dev

python-is-pythons schedtool ccache libt infos Tibncurses 1zop tmux libssl-dev

patchelf apktool dos2unix git-its default-jak libxml-simple-perl ripgrep clang-11 > /dev/null

    - name: Download Neutron Toolchain

      run: bash hani-ci.sh--tools

    - name: build gokulgethu-lillium

      run: bash hani-ci.sh-build

    - name: Upload kernel

      uses: actions/upload-artifact@tv3

      with:

         name: gokulgethu-lillium

         path: 4.19-gokulgethu.*-lillium-chime*.zip
